# docker-compose.yml
# 定义服务
services:
  # 服务的名称
  face-rec-service:
    image: registry.cn-hangzhou.aliyuncs.com/canstack/face-rec-service:1.0.0
    build:
      context: .
      dockerfile: Dockerfile

    container_name: face_recognition_service

    ports:
      - "${SERVER__PORT}:${SERVER__PORT}" # FastAPI
      - "${WEBUI__PORT}:${WEBUI__PORT}" # Streamlit

    environment:
      - HOST__IP=${HOST__IP}
      - SERVER__PORT=${SERVER__PORT}
      - WEBUI__PORT=${WEBUI__PORT}

    # GPU 资源配置 (Docker Compose 推荐方式)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    # 重启策略: 除非手动停止，否则容器总是在退出后重启
    restart: unless-stopped