# docker-compose.yml
services:
  face-rec-service:
    image: registry.cn-hangzhou.aliyuncs.com/canstack/face-rec-service:1.0.0
    build:
      context: .
      dockerfile: Dockerfile

    container_name: face_recognition_service

    ports:
      - "${SERVER__PORT:-12010}:${SERVER__PORT:-12010}"  # FastAPI
      - "${WEBUI__PORT:-12011}:${WEBUI__PORT:-12011}"    # Streamlit

    environment:
      # 服务器配置
      - SERVER__HOST=${SERVER__HOST:-0.0.0.0}
      - SERVER__PORT=${SERVER__PORT:-12010}
      # Web UI配置
      - WEBUI__HOST=${WEBUI__HOST:-0.0.0.0}
      - WEBUI__PORT=${WEBUI__PORT:-12011}
      # 其他配置
      - HOST__IP=${HOST__IP:-localhost}
      - APP__DEBUG=${APP__DEBUG:-false}
      - LOGGING__LEVEL=${LOGGING__LEVEL:-INFO}

    volumes:
      - ./.env:/app/.env

    # GPU 资源配置
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    # 重启策略
    restart: unless-stopped